# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.S')
CPPPATH = [cwd]

group = DefineGroup('drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
