+incdir+$SIM_ROOT_DIR/tools/tdb_reader
$SIM_ROOT_DIR/tools/tdb_reader/tdb_reader.a
top.sv
$SIM_ROOT_DIR/rtl/core_top.sv
$SIM_ROOT_DIR/rtl/fetch.sv
$SIM_ROOT_DIR/rtl/decode.sv
$SIM_ROOT_DIR/rtl/rename.sv
$SIM_ROOT_DIR/rtl/readreg.sv
$SIM_ROOT_DIR/rtl/issue.sv
$SIM_ROOT_DIR/rtl/execute_alu.sv
$SIM_ROOT_DIR/rtl/execute_bru.sv
$SIM_ROOT_DIR/rtl/execute_csr.sv
$SIM_ROOT_DIR/rtl/execute_div.sv
$SIM_ROOT_DIR/rtl/execute_lsu.sv
$SIM_ROOT_DIR/rtl/execute_mul.sv
$SIM_ROOT_DIR/rtl/wb.sv
$SIM_ROOT_DIR/rtl/commit.sv
$SIM_ROOT_DIR/rtl/branch_predictor.sv
$SIM_ROOT_DIR/rtl/bus.sv
$SIM_ROOT_DIR/rtl/checkpoint_buffer.sv
$SIM_ROOT_DIR/rtl/clint.sv
$SIM_ROOT_DIR/rtl/csrfile.sv
$SIM_ROOT_DIR/rtl/uart_controller.sv
$SIM_ROOT_DIR/rtl/csr_access_check.sv
$SIM_ROOT_DIR/rtl/data_selector.sv
$SIM_ROOT_DIR/rtl/execute_feedback.sv
$SIM_ROOT_DIR/rtl/interrupt_interface.sv
$SIM_ROOT_DIR/rtl/issue_queue.sv
$SIM_ROOT_DIR/rtl/list_enabled_item_id.sv
$SIM_ROOT_DIR/rtl/multififo.sv
$SIM_ROOT_DIR/rtl/phy_regfile.sv
$SIM_ROOT_DIR/rtl/ras.sv
$SIM_ROOT_DIR/rtl/rat.sv
$SIM_ROOT_DIR/rtl/rob.sv
$SIM_ROOT_DIR/rtl/store_buffer.sv
$SIM_ROOT_DIR/rtl/tcm.sv
$SIM_ROOT_DIR/rtl/mem_dual_port_rw.sv
$SIM_ROOT_DIR/rtl/fifo.sv
$SIM_ROOT_DIR/rtl/handshake_dff.sv
$SIM_ROOT_DIR/rtl/port.sv
$SIM_ROOT_DIR/rtl/expand_one.sv
$SIM_ROOT_DIR/rtl/count_one.sv
$SIM_ROOT_DIR/rtl/parallel_finder.sv
$SIM_ROOT_DIR/rtl/priority_finder.sv
+incdir+$SIM_ROOT_DIR/rtl